import sys
import glob
import os.path

# import variables from other scons files
Import( '*' )
env = masterEnv.Clone()

env.AppendUnique( **mergeOptions( utdataflow_all_options, utvision_all_options, utcomponents_options ) )
env.AppendUnique( LIBS = boost_libs( [ 'thread' ] ) )

# create component libraries
comp_sources = globSourceFiles( '*.cpp' )

# setup environment
env.AppendUnique( **mergeOptions( utvision_options, opencv_options, lapack_options ) )
env.AppendUnique( LIBS = boost_libs( [ 'thread' ] ) )
env.Replace( no_import_lib = 1 )


# compile components as shared libraries
setupComponentBuild(env, comp_sources, 'visioncomponents')
