import os

# import variables from other scons files
Import( '*' )


if not have_utvision or not have_lapack:
	print "utVision or lapack missing -- not building vision apps"
	success = False
	Return('success')	

env = masterEnv.Clone()

# setup compiler and linker flags
env.AppendUnique( **utcore_all_options )
env.AppendUnique( **utfacade_all_options )
if have_utvision:
	env.AppendUnique( **utvision_all_options )
	env.AppendUnique( **opencv_options )



#env.AppendUnique( LIBS = boost_libs( [ "serialization", "program_options", "system", "filesystem", "regex" ] ) )


allUtilSources = []

# find all subdirectories
sources = globSourceFiles( '*.cpp' )
setupAppBuild( env, sources, "CornerFinder", 'utApps')	


