import glob

Import( '*' )

# create a common build environment for all drivers
utComponentEnv = masterEnv.Clone()

utComponentEnv.AppendUnique( **mergeOptions( utcore_options, utdataflow_options, utvision_options, boost_options, tinyxml_options, log4cpp_options, utcomponents_options, tbb_options ) )
utComponentEnv.AppendUnique( LIBS = boost_libs( [ 'thread' ] ) )

Export( 'utComponentEnv' )

# glob all SConscript files in subdirectories
sconsfiles = globSourceFiles( "*/SConscript" )

# recurse into subdirectories and export driver build environment
SConscript( sconsfiles, [ 'utComponentEnv' ] )
success = True
Return('success')
